name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run build
              run: cargo build --verbose
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run tests
              run: |
                  cargo build
                  cargo test --verbose
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run Rustfmt
              run: cargo fmt -- --check
            
            - name: Run Clippy
              run: cargo clippy --verbose
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Run dependency security audit
              run: cargo install cargo-audit && cargo --verbose audit

            - name: Install cargo-outdated
              run: cargo install cargo-outdated

            - name: Run depedency version audit
              run: cargo outdated --root-deps-only --verbose --exit-code 1

